# CI values for Pipelines
databaseUpgradeReady: true
global:
  customInitContainersBegin: |
   - name: "custom-init-begin-global"
     image: "releases-docker.jfrog.io/alpine:3.14.2"
     imagePullPolicy: "IfNotPresent"
     command:
       - 'sh'
       - '-c'
       - 'touch {{ .Values.pipelines.mountPath }}/init-begin-global'
     volumeMounts:
       - mountPath: "{{ .Values.pipelines.mountPath }}"
         name: jfrog-pipelines-folder
  customInitContainers: |
   - name: "custom-init-global"
     image: "releases-docker.jfrog.io/alpine:3.14.2"
     imagePullPolicy: "IfNotPresent"
     command:
       - 'sh'
       - '-c'
       - 'touch {{ .Values.pipelines.mountPath }}/init-global'
     volumeMounts:
       - mountPath: "{{ .Values.pipelines.mountPath }}"
         name: jfrog-pipelines-folder
  customVolumes: |
   - name: custom-volume-global
     emptyDir:
       sizeLimit: 100Mi
  customSidecarContainers: |
   - name: "sidecar-list-global"
     image: "releases-docker.jfrog.io/alpine:3.14.2"
     imagePullPolicy: "IfNotPresent"
     securityContext:
       allowPrivilegeEscalation: false
       capabilities:
         drop:
           - NET_RAW
     command: ["sh","-c","echo 'Sidecar is running in global' >> /scriptsglobal/sidecar.txt; cat /scriptsglobal/sidecar.txt; while true; do sleep 30; done"]
     volumeMounts:
       - mountPath: "{{ .Values.pipelines.mountPath }}"
         name: jfrog-pipelines-folder
     resources:
       requests:
         memory: "32Mi"
         cpu: "50m"
       limits:
         memory: "128Mi"
         cpu: "100m"
pipelines:
  jfrogUrl: http://artifactory.rt:8082
  jfrogUrlUI: http://artifactory.rt:8082
  api:
    externalUrl: http://pipelines.test.com
  msg:
    uiUserPassword: password
  customSidecarContainers: |
   - name: "sidecar-list-local"
     image: "releases-docker.jfrog.io/alpine:3.14.2"
     imagePullPolicy: "IfNotPresent"
     securityContext:
       allowPrivilegeEscalation: false
       capabilities:
         drop:
           - NET_RAW
     command: ["sh","-c","echo 'Sidecar is running in global' >> /scriptsglobal/sidecar.txt; cat /scriptsglobal/sidecar.txt; while true; do sleep 30; done"]
     volumeMounts:
       - mountPath: "{{ .Values.pipelines.mountPath }}"
         name: jfrog-pipelines-folder
     resources:
       requests:
         memory: "32Mi"
         cpu: "50m"
       limits:
         memory: "128Mi"
         cpu: "100m"
postgresql:
  postgresqlPassword: password
  persistence:
    enabled: false

rabbitmq:
  auth:
    password: password
  persistence:
    enabled: false

redis:
  master:
    persistence:
      enabled: false
