# Leave this file empty to ensure that CI runs builds against the default configuration in values.yaml.
# If this is an upgrade over an existing Mission Control 4.x, explicitly pass 'unifiedUpgradeAllowed=true' to upgrade
unifiedUpgradeAllowed: true
databaseUpgradeReady: true
distribution:
  jfrogUrl: http://artifactory.rt:8082
  persistence:
    enabled: false
# To Fix ct tool --reuse-values - PASSWORDS ERROR: you must provide your current passwords when upgrade the release
postgresql:
  postgresqlPassword: password
  persistence:
    enabled: false
redis:
  persistence:
    enabled: false
